export const LOGIN_SUBMIT = "LOGIN_SUBMIT";
export const FETCH_INVOICE = "FETCH_INVOICE";
export const FETCH_SINGLE_INVOICE = "FETCH_SINGLE_INVOICE";
export const ADD_INVOICE = "ADD_INVOICE";
export const DELETE_INVOICE = "DELETE_INVOICE";
export const UPDATE_INVOICE = "UPDATE_INVOICE";